FROM rancherlabs/rio-website:build
ENV HUGO_ENV dev

VOLUME ["/site"]
VOLUME ["/site/public"]
VOLUME ["/site/static"]
WORKDIR /site

# Expose default hugo port
EXPOSE 80

ENTRYPOINT ["hugo"]
CMD ["server"]
