FROM rancherlabs/rio-website:build as build
ENV HUGO_ENV staging

WORKDIR /build

COPY archetypes archetypes
COPY config.toml /build/
COPY content content
COPY data data
COPY layouts layouts
COPY scripts scripts
COPY static static
COPY themes themes

RUN hugo

# Make sure something got built
RUN stat /build/public/index.html

FROM nginx
COPY --from=build /build/public /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
