FROM debian:stretch

# Download and install hugo
ENV HUGO_VERSION 0.46
ENV HUGO_BINARY hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz

WORKDIR /tmp
ADD https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY} /tmp/hugo.tar.gz
RUN tar -xzf hugo.tar.gz && mv hugo /usr/bin/hugo && rm /tmp/hugo.tar.gz
