FROM rancherlabs/rio-website:build
ENV HUGO_ENV dev

VOLUME ["/site"]
WORKDIR /site

RUN mkdir -p /build

# Expose default hugo port
EXPOSE 80

ENTRYPOINT ["hugo" ,"server", "--renderToDisk", "--destination","/build"]
