#!/usr/bin/env bash

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

dasherize() {
  # $@: Hello World: stuff
  # Out: hello-world-stuff

  #         To lower case               Odd chars to hyphen            Combine hyphens      No leading or trailing hyphens
  echo $@ | awk '{print tolower($0)}' | sed -e 's/[^A-Za-z0-9-]/-/g' | sed -e 's/--*/-/g' | sed -e 's/^--*//' -e 's/--*$//'
}

print_help()
{
  cat 1>&2 <<EOF
Usage:

[-s SECTION] post title

-s SECTION - Content section to create

EOF
}

SECTION="blog"
TODAY=$(date +'%Y-%m-%d')
YEAR=$(date +'%Y')

while getopts ":s:" opt;do
  SECTION="${OPTARG}"
done
shift $(expr $OPTIND - 1 )

TITLE=$@
DASHERIZE=$(dasherize $TITLE)
URL="/${SECTION}/${DASHERIZE}"
FILENAME="${SECTION}/${YEAR}/${TODAY}-${DASHERIZE}.md"
ABSOLUTE="$(pwd)/content/$FILENAME"

echo "Title: ${TITLE}"
echo "File: ${FILENAME}"
echo "URL: ${URL}"

docker run --rm -it -v $(pwd):/site --entrypoint=hugo rancherlabs/website:dev new $FILENAME >/dev/null 2>&1
sed -i.bak "s^title: \"\"^title: \"${TITLE}\"^g" $ABSOLUTE
sed -i.bak "s^url: \"\"^url: \"${URL}\"^g" $ABSOLUTE
rm $ABSOLUTE.bak
echo "Created $ABSOLUTE"
open $ABSOLUTE
