#!/bin/bash

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

echo "Pulling Builder..." && \
docker pull rancher/rio-website:build && \
echo "Building Image..." && \
docker build --no-cache -t rancher/rio-website:latest . && \
echo "Pushing Image..." && \
docker push rancher/rio-website:latest && \
echo "OK"
